pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        def className = "HelloWorld"
        sh "mvn clean compile exec:java -Dexec.mainClass=='${className}'"

      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node hello.js'
      }
    }
  }
}
