pipeline {
    agent none
    stages {
        stage('Front-end') {
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                sh 'node hello.js'
            }
        }
        stage('Back-end') {
            agent {
                docker { image 'maven:3.8.1-adoptopenjdk-11' }
            }
            steps {
                sh 'mvn -B -DskipTests clean package' // Build the Java project with Maven
                sh 'java -jar target/HelloWorld.jar' // Run the Java program
            }
        }
    }
}
